name: 'Build a Quarkus native application'
description: 'Build a Quarkus native application'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  outputName:
    description: name of the resulting executable binary file
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile' 
  args: 
    - ${{ inputs.outputName }}
